name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['2.7', '3.9', '3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install numpy pytest
    - name: Test
      run: |
        python setup.py build_ext --inplace -t build
        cd pyRMSD/test
        PYTHONPATH=../.. pytest testRMSDCalculators.py testSymmTools.py
